Shift things, update Debian files

diff --git a/debian/postinst b/debian/postinst
--- a/debian/postinst
+++ b/debian/postinst
@@ -1,6 +1,22 @@
 #!/bin/sh
 
-gtk-update-icon-cache /usr/share/icons/Rainier
+set -e
+
+write_cache()
+{
+if [ -x /usr/bin/gtk-update-icon-cache ]; then
+    if ! gtk-update-icon-cache --force --quiet /usr/share/icons/elementary; then
+        echo "WARNING: icon cache generation failed"
+    fi
+fi
+}
+
+if [ "$1" = "triggered" ]; then
+    write_cache
+    exit 0
+fi
+
+write_cache
 
 # Script for fixing hardcoded icons. Written and maintained on GitHub
 # at https://github.com/Foggalong/hardcode-fixer - addtions welcome!
